// Assembly UnityEditor, Version 0.0.0.0

[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.Advertisements")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.PackageManager")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Automation")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.PureCSharpTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.IntegrationTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.IntegrationTests.UnityAnalytics")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.Graphs")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.WP8.Extensions")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.Metro.Extensions")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.iOS.Extensions")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.AppleTV.Extensions")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.Xbox360.Extensions")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.BB10.Extensions")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.Android.Extensions")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.Tizen.Extensions")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.PS3.Extensions")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.SamsungTV.Extensions")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.XboxOne.Extensions")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.PSP2.Extensions")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.PS4.Extensions")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.WiiU.Extensions")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.PSM.Extensions")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.WebGL.Extensions")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.LinuxStandalone.Extensions")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.WindowsStandalone.Extensions")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.OSXStandalone.Extensions")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.Networking")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.N3DS.Extensions")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.EditorTestsRunner")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.TreeEditor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.RuntimeTests.Framework")]
[assembly: UnityEngine.AssemblyIsEditorAssembly]
[assembly: System.Runtime.CompilerServices.Extension]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]

