// Assembly UnityEngine, Version 0.0.0.0

[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.Advertisements")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.PureCSharpTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("DynamicProxyGenAssembly2")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.Graphs")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.Xbox360.Extensions")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEditor.WiiU.Extensions")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.Physics")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.Terrain")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.TerrainPhysics")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.Networking")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.Cloud")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.Cloud.Service")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.Analytics")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.Advertisements")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.Purchasing")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Automation")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.IntegrationTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.IntegrationTests.UnityAnalytics")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.IntegrationTests.Framework")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.RuntimeTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.RuntimeTests.Framework")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.RuntimeTests.Framework.Tests")]
[assembly: System.Runtime.CompilerServices.Extension]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("UnityEngine.Advertisements")]
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum, SkipVerification=true)]

